### ISSUE TITLE
[Tests] Logger tests are flaky

### ISSUE THREAD

**Issue by mandel-macaque** [dotnet/xharness#220]
The FileLogger tests give problems on Windows in some cases due to the fact that the file is in used. Does not always happen.

**Comment by premun** [comment]
I have seen this happen before when fixing (back then) Xamarin unit tests on Windows:
https://github.com/xamarin/xamarin-macios/pull/8208

Most of them did File.Create which gets you a handle instead of WriteAllText which just does the write. It will be something similar.

We also have another case here where we have a flakey test that scans Console.Out contents and that can go wrong when running tests in parallel.

I will take this and fix it easy
