### ISSUE TITLE
Create a "default" or "common" instrumentation base

### ISSUE THREAD

**Issue by mattleibow** [dotnet/xharness#383]
When I am creating my Android apps, I have to implement an `Instrumentation` class. This is fine and works very well, however, I can't help but feel that this is somewhat "boilerplate". And I am sure I am doing it wrong.

For example, this is my edition: https://github.com/xamarin/Essentials/blob/cc08b9608999f40db02501cd27f3c7086e60eba7/DeviceTests/DeviceTests.Android/TestInstrumentation.cs

Or an older version: https://github.com/Azure/azure-mobile-apps-net-client/pull/559/files#diff-57ff0bad3452e9223031b3cdbbe553100132531c82f20d59534afe8246c0e97d

It works, but I am not doing the parsing of arguments for which test methods to run or properly set the `return-code`.

Maybe there should be some additional NuGet that adds the default logic for all of this and then have points to override various properties.

**Comment by mattleibow** [comment]
This is actually a good thing for most because the bit for parsing the CLI arguments to do the filter and excludes is a non-trivial task. Doing this once in a library will be useful.

**Comment by mattleibow** [comment]
I have another for reference that is more up-to-date: https://github.com/xamarin/Essentials/blob/main/DeviceTests/DeviceTests.Android/TestInstrumentation.cs

**Comment by mattleibow** [comment]
Also, might be worth adding logic to automatically return the results file as I assume that is what most people actually want from this. Or at least have a way to easily get them without having to do it manually.

**Comment by greenEkatherine** [comment]
I discussed my change with the team today and it seems that it cannot be merged in current state. The crucial point is that for default Instrumentation the dependency to `Instrumentation` and `Bundle` should be set which means dependency to Xamarin in either way. Taking this into account it doesn't look like XHarness is a good place for such base Instrumentation library since it's not generic and add extra dependency that we decided to avoid.

The solution that comes to my mind is splitting this change. Instrumentation base class' part is going to be created in Xamarin but the XHarness library will provide `TestEntryPoint` and dealing with test results path, test filtering etc. @mattleibow does it sound good for you?

@tkapin @premun please feel free to add your thoughts if I miss anything

**Comment by mattleibow** [comment]
Sounds good. We can create a Xamarin + XHarness package and just do what you did in the PR.

I was playing around and I think we can do stuff. However, it will be nice to be able to put this code in this repo. It is just an `net6-android;net6-ios` project. and since this is a new package, we do not actually affect the dependency for the rest of the packages.

**Comment by premun** [comment]
Yeah, that would also be doable and I think that would actually make sense. Only problem is that we are a bit behind on .NET in XHarness (.NET Core 3.1), so we need to bump that first to be able to use these new monikers

**Comment by tkapin** [comment]
Just to make sure we are on the same page, XHarness should be the shared tooling used by multiple clients, such as mono, XMAUI, perhaps the CLR in the future and as such, it shouldn't contain any dependency on these projects (with an obvious exception of the .net runtime as it's written in C# tool). This also applies on other potential entities in the `dotnet/xharness` repo.

**Comment by greenEkatherine** [comment]
I've created a separate issue for the suggested solution #480

**Comment by tkapin** [comment]
Thank you @greenEkatherine , I'm closing this issue then to make a clear distinction between the two approaches.
