### ISSUE TITLE
Use structured logging

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet/xharness#568]
I noticed the code base is interpolating log messages such as:

https://github.com/dotnet/xharness/blob/83721524941aff6b628b0b943a8c193e1829985d/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidRunCommand.cs#L168

In order to receive the template separate from the variable and allow structured logging, the log message should be recorded instead as:

```
logger.LogError("Un-parse-able value for '{ReturnCodeVariableName}' : '{resultValues}'",
    ReturnCodeVariableName, resultValues[ReturnCodeVariableName]);
```

[More about this on the logging docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#log-message-template).

I thought of opening a PR to address this but since it's quite a bit of work, I realized it's best I raise this to check this change is wanted.

**Comment by premun** [comment]
Thanks for this. I understand that it's always better to structure information rather than not in case we start using this somehow in the future.
I know that for systems like Application Insights or so we can query the structured data better but I guess we just didn't pay much attention to this since we are a command line tool with console logs only. But again, if we would start offering XHarness as a cloud solution, we would welcome this capability.

I don't think we are currently able to pro-actively invest in this but all contributions are welcome and appreciated!

**Comment by bruno-garcia** [comment]
Cool. I'll see if I open a PR for this soon.

Another motivation for structured logging is for a tool like [Sentry](https://github.com/getsentry/sentry-dotnet) that will use the template for grouping, but display the interpolated message to users. This is useful because a `LogError` becomes an event that can raise an alert (the first time it lands). But multiple occurrences of it would not trigger more alerts.

**Comment by premun** [comment]
This issue would probably require considerable effort. We won't be able to fund this currently. The solution now shows hints about these issues in the IDE as build messages, so we know about this every time we work with the code as a reminder and thus I think we can close this issue
