### ISSUE TITLE
PACKAGE_INSTALLATION_FAILURE happening on some Android work items

### ISSUE THREAD

**Issue by steveisok** [dotnet/xharness#597]
From my observation today, this seems pretty flaky and hasn't yet impacted too many work items.

The failures occur on the Android arm64 (device) leg.  Here are examples:

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8f7622f0765e44d792/System.ComponentModel.EventBasedAsync.Tests/console.6f6858ae.log?sv=2019-07-07&se=2021-06-02T19%3A06%3A59Z&sr=c&sp=rl&sig=sAw%2FaG5opryYuZsSLmO2g6m3SoYh3ip3Wo%2F9d24zYmw%3D

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8f7622f0765e44d792/System.Globalization.Extensions.Tests/console.23ae2187.log?sv=2019-07-07&se=2021-06-02T19%3A06%3A59Z&sr=c&sp=rl&sig=sAw%2FaG5opryYuZsSLmO2g6m3SoYh3ip3Wo%2F9d24zYmw%3D

**Comment by steveisok** [comment]
It looks like this might be machine/device specific.  Namely `DNCENGWIN-020 & DNCENGWIN-022`

**Comment by greenEkatherine** [comment]
I logged in 4 machines to check. DNCENGWIN-50 and DNCENGWIN-120 were affected but they are ok now. DNCENGWIN-20 and DNCENGWIN-71 were not resolved. I see that there are adb server running on them and I think this is the root cause. It may not be killed since previous run so when we get this error we should try to kill it, then start and try to install apk.

**Comment by premun** [comment]
This is a nice find.

Side note: In iOS we kill the `Simulator.app` in Helix SDK before the work item starts - if you confirm that already running/hanging adb process is the cause, it's totally fine killing before every work item just to be sure.

So you should decide where you draw the line between what XHarness does and what is the desired machine state and put that in the layer that is Helix SDK. Maybe developers using XHarness don't want their ADB servers to be killed because they have some other things running or maybe they would actually appreciate.

**Comment by greenEkatherine** [comment]
What if to kill adb only in case when `adb install` command returns time out? We do it now but in case when install returns broken pipe

**Comment by premun** [comment]
Yeah, sure, makes sense then. I don't know the Android world much so just adding my two cents. If we already handle adb like this then it's good to do the same for this case as well

**Comment by greenEkatherine** [comment]
I cannot reproduce it to test my fix, so will compare statistics after merge. I considered three types of solutions for this issue:

1. Increase adb timeout - but it is set up to 5 mions and it should be enough
2. Restart adb (my fix)
3. Change usb port - I think it is not the case because there are no machines where all installations are timed out
