### ISSUE TITLE
Redundant retries on the same machines

### ISSUE THREAD

**Issue by greenEkatherine** [dotnet/xharness#749]
Tests running on API 21 with job id `eacc4c4f-20f8-479b-89c4-1f7a6c52022b` have retries on each item, executed on the same machine. In case of VMs and emulators it probably doesn't make sense.

**Comment by greenEkatherine** [comment]
Helix SDK reboots VM and requests infra retry but jobs catch the same machine with high probability because going into queue faster than reboot request. 

We considered an option to kill VM in case we cannot find an emulator. I discussed it with @MattGal and agreed with his opinion that by killing VMs we might end up killing all queue if some test or script will cause the same error. 

At this point it seems easer and safer to ensure that emulators start instead of workaround on Helix SDK side. Later if we return to that idea it will require to set up vary strict alert on number of killed machines.

**Comment by MattGal** [comment]
> At this point it seems easer and safer to ensure that emulators start(#754 ) instead of workaround on Helix SDK side. Later if we return to that idea it will require to set up vary strict alert on number of killed machines.

I strongly agree.  I think since we don't know what leads to them being in this state, some kind of deeper dump about the state of the emulator could maybe be made in the case where it doesn't start (and piggyback its way out of the Helix client either through App Insights traces or the UPLOAD_ROOT folder for analysis).  There ought to be some kind of way to fully reinstall the thing that the startup daemon of the emulator artifact could fall back to if things are truly dead.
